env: "local"

default_ttl: 1

http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 30s

kafka:
  addr: "kafka:9092"
  topic: "hash_queue"
  groupid: "1"

mysql:
  dsn: "pasteuser:pastepass@tcp(mysql:3306)/pastebin?parseTime=true"

minio:
  endpoint: "localhost:9000"
  user: "minioadmin"
  password: "minioadmin"
  bucket: "pastes"
  useSSL: false